#  1a. Numpy exercises

1. Import the numpy package under the name `np`

`hint: import … as`

In [16]:
import numpy as np

np.random.seed(42)  # For reproducibility


2. Create a zero vector of size 10

`hint: np.zeros`



In [17]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

3. Create a vector with values ranging from 0 to 100

`hint: arange`

In [18]:
np.arange(0, 100, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

4. Create a 10x10 matrix with random values and find the minimum, maximum, and mean values. Normalize the said matrix

`hint: min, max, ...`

In [19]:
rand_matrix = np.random.random(size=(10, 10))

min_val = np.min(rand_matrix)
max_val = np.max(rand_matrix)
mean_val = np.mean(rand_matrix)

min_max_diff = max_val - min_val

normalized_matrix = (rand_matrix - min_val)/min_max_diff
linalg_norm_matrix = np.linalg.norm(normalized_matrix) # NOTE: This is a simple approach. Just us that one!

print("Minimum value:\n", min_val)
print("Maximum value:\n", max_val)
print("Mean value:\n", mean_val)

print("Manually calculated norm:\n", linalg_norm_matrix)
print("Numpy calculated norm:\n", np.linalg.norm(normalized_matrix))

Minimum value:
 0.005522117123602399
Maximum value:
 0.9868869366005173
Mean value:
 0.47018074337820936
Manually calculated norm:
 5.61390454624632
Numpy calculated norm:
 5.61390454624632


5. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

`hint: np.sqrt, np.arctan2`

In [20]:
coor_matrix = np.random.random(size=(10, 2))

radius_matrix = np.sqrt(np.sum(coor_matrix ** 2, axis=1))
angle_matrix = np.arctan2(coor_matrix[:, 0], coor_matrix[:, 1])

print("Coordinates:\n", coor_matrix)
print("Radius:\n", radius_matrix)
print("Angle:\n", angle_matrix)

polar_matrix = np.column_stack((radius_matrix, angle_matrix))

print("Polar coordinates:\n", polar_matrix)


Coordinates:
 [[0.03142919 0.63641041]
 [0.31435598 0.50857069]
 [0.90756647 0.24929223]
 [0.41038292 0.75555114]
 [0.22879817 0.07697991]
 [0.28975145 0.16122129]
 [0.92969765 0.80812038]
 [0.63340376 0.87146059]
 [0.80367208 0.18657006]
 [0.892559   0.53934224]]
Radius:
 [0.63718601 0.59788279 0.94118198 0.85980909 0.24140113 0.33158439
 1.2318264  1.07733183 0.82504375 1.04285743]
Angle:
 [0.049345   0.55363413 1.30272573 0.49757433 1.24624039 1.06304334
 0.85524409 0.6285067  1.34268977 1.02724663]
Polar coordinates:
 [[0.63718601 0.049345  ]
 [0.59788279 0.55363413]
 [0.94118198 1.30272573]
 [0.85980909 0.49757433]
 [0.24140113 1.24624039]
 [0.33158439 1.06304334]
 [1.2318264  0.85524409]
 [1.07733183 0.6285067 ]
 [0.82504375 1.34268977]
 [1.04285743 1.02724663]]


6. Create random vector of size 10 and replace the maximum value by 0

`hint: argmax`

In [37]:
a = np.random.rand(10)

print("Vector shape:", a.shape)
print("Vector:", a)

a[np.argmax(a)] = 0

print("----------")
print("Resulting vector:", a)

Vector shape: (10,)
Vector: [0.80936116 0.81011339 0.86707232 0.91324055 0.5113424  0.50151629
 0.79829518 0.64996393 0.70196688 0.79579267]
----------
Resulting vector: [0.80936116 0.81011339 0.86707232 0.         0.5113424  0.50151629
 0.79829518 0.64996393 0.70196688 0.79579267]


7. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.

`hint: np.meshgrid`

In [48]:
x = np.arange(0, 1.1, 0.1)
print(x)

X, Y = np.meshgrid(x, x)
# print("Coordinates X: \n", X)
# print("Coordinates Y: \n", Y)

# NOTE: A structured array in numpy is an array with labels on the columns. It can be created like below:
structured_array = np.zeros(X.shape, dtype=[('x', float), ('y', float)])

print("X shape: ", X.shape)
print("Y shape: ", Y.shape)
print("Structured array shape: ", structured_array.shape)
print("----------")

# We can then assign the value to the structured array:
structured_array['x'] = X
structured_array['y'] = Y

print("Structured array:\n", structured_array)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
X shape:  (11, 11)
Y shape:  (11, 11)
Structured array shape:  (11, 11)
----------
Structured array:
 [[(0. , 0. ) (0.1, 0. ) (0.2, 0. ) (0.3, 0. ) (0.4, 0. ) (0.5, 0. )
  (0.6, 0. ) (0.7, 0. ) (0.8, 0. ) (0.9, 0. ) (1. , 0. )]
 [(0. , 0.1) (0.1, 0.1) (0.2, 0.1) (0.3, 0.1) (0.4, 0.1) (0.5, 0.1)
  (0.6, 0.1) (0.7, 0.1) (0.8, 0.1) (0.9, 0.1) (1. , 0.1)]
 [(0. , 0.2) (0.1, 0.2) (0.2, 0.2) (0.3, 0.2) (0.4, 0.2) (0.5, 0.2)
  (0.6, 0.2) (0.7, 0.2) (0.8, 0.2) (0.9, 0.2) (1. , 0.2)]
 [(0. , 0.3) (0.1, 0.3) (0.2, 0.3) (0.3, 0.3) (0.4, 0.3) (0.5, 0.3)
  (0.6, 0.3) (0.7, 0.3) (0.8, 0.3) (0.9, 0.3) (1. , 0.3)]
 [(0. , 0.4) (0.1, 0.4) (0.2, 0.4) (0.3, 0.4) (0.4, 0.4) (0.5, 0.4)
  (0.6, 0.4) (0.7, 0.4) (0.8, 0.4) (0.9, 0.4) (1. , 0.4)]
 [(0. , 0.5) (0.1, 0.5) (0.2, 0.5) (0.3, 0.5) (0.4, 0.5) (0.5, 0.5)
  (0.6, 0.5) (0.7, 0.5) (0.8, 0.5) (0.9, 0.5) (1. , 0.5)]
 [(0. , 0.6) (0.1, 0.6) (0.2, 0.6) (0.3, 0.6) (0.4, 0.6) (0.5, 0.6)
  (0.6, 0.6) (0.7, 0.6) (0.8

8. Having a scalar `x` and a random vector `v`, find a value in `v` that is closest to `x`

`hint: argmin`

In [ ]:
import random

V = np.random.random(size=(10, 10)) * 1000
x = random.randint(1, 1000)

# print("Random number x:", x)
# print("Random matrix V:\n", V)

diff_matrix = np.abs(V - x)
closest_index = np.unravel_index(np.argmin(diff_matrix), V.shape) # NOTE: unravel_index converts the flat index to a tuple of indices for the 2D array
print("Index of closest value to x in V:", closest_index)
print("Closest value to x in V: \n", V[closest_index])


Random number x: 63
Random matrix V:
 [[334.24389082 770.91220375 106.59825313  75.13778174 728.1887562
  495.49131621 688.40239643 434.8273386  246.40203324 819.10231767]
 [799.41587897 694.69647085 272.14513723 590.23066687 360.97389694
   91.58207333 917.31357546 136.81863092 950.23735382 446.00577296]
 [185.13292884 541.90094738 872.94583588 732.22488641 806.56114786
  658.78336671 692.27656452 849.19565157 249.66800886 489.42496364]
 [221.20944182 987.668008   944.05933969  39.42681137 705.57517252
  925.24831742 180.57534513 567.94523055 915.48829759  33.94597859]
 [697.42026725 297.34900737 924.39619538 971.05824517 944.26648911
  474.21421666 862.04265099 844.54939854 319.10047324 828.91547415]
 [ 37.00763472 596.26987848 230.00883729 120.56688578  76.95320163
  696.28877588 339.87496377 724.76677153  65.3563408  315.29033783]
 [539.49129238 790.72316484 318.75250293 625.89137644 885.97774824
  615.86318818 232.95947475  24.40078156 870.0988739   21.26941085]
 [874.70167268 528

9. Consider a random vector with shape (100,2) representing coordinates, find point by point distances and put them in a (100,100) array.

In [81]:
V = np.random.random(size=(10, 2)) * 1000
diff = V[:, np.newaxis, :] - V[np.newaxis, :, :]  # Broadcasting to calculate pairwise differences

print(np.sqrt(np.sum(diff ** 2, axis=-1)))  # Squared differences

[[  0.         358.57381763 264.81855806 455.10743708 534.58645862
  510.6197138  194.46886073 403.39641694 138.4638951  154.20797144]
 [358.57381763   0.         620.99458765 812.97471859 858.63461918
  509.26512058 527.4972946  717.76298615 379.54577642 510.92452817]
 [264.81855806 620.99458765   0.         210.71512734 384.88993287
  685.54622139 125.58505143 214.9904281  323.92110423 110.62300064]
 [455.10743708 812.97471859 210.71512734   0.         250.05949307
  771.87069618 335.15668224 325.88093026 469.47307748 309.21241885]
 [534.58645862 858.63461918 384.88993287 250.05949307   0.
  659.19392265 500.08456047 560.93836903 479.4128556  435.31244433]
 [510.6197138  509.26512058 685.54622139 771.87069618 659.19392265
    0.         682.61898062 883.47634533 382.00731248 605.4953472 ]
 [194.46886073 527.4972946  125.58505143 335.15668224 500.08456047
  682.61898062   0.         209.3212573  301.22568805  87.78037923]
 [403.39641694 717.76298615 214.9904281  325.88093026 560.93836

10. Create a random (100, 100) matrix with values from 0 to 1. Turn all values lower than 0.5 into 0.0

In [94]:
V = np.random.random(size=(100, 100))
min_matrix = np.zeros(V.shape) + 0.5

less_matrix = np.where(V < min_matrix, np.zeros(V.shape), V)
print(less_matrix)

[[0.57532798 0.         0.         ... 0.         0.         0.77557641]
 [0.         0.85779958 0.         ... 0.         0.         0.5153355 ]
 [0.         0.         0.         ... 0.63832309 0.         0.        ]
 ...
 [0.         0.         0.57818373 ... 0.86700308 0.94554351 0.        ]
 [0.87622721 0.         0.99049921 ... 0.         0.5784052  0.        ]
 [0.         0.         0.59506551 ... 0.         0.         0.        ]]


11. Do a dot product of two matrices and print only the diagonal values.

In [ ]:
X = np.random.random(size=(10, 10))
Y = np.random.random(size=(10, 10))

D = np.dot(X, Y)  # Matrix multiplication

# print(D)

idx = 0
for (x,y), val in np.ndenumerate(D):
    if x == y and idx == x:
        print(val)
        idx += 1


1.896345807712728
2.0582090757414875
2.9303219719197267
1.748022223861739
2.3730962278098047
2.7623668313679706
1.5104512508289059
1.9712702068147676
2.439827989675519
2.3455285944209003


12. Swap two rows of a matrix.

In [100]:
X = np.random.random(size=(10, 10))

row_zero = X[0, :].copy()
row_one = X[1, :].copy()

print("Original X:\n", X)

X[0, :] = row_one
X[1, :] = row_zero

print("Modified X:\n", X)

Original X:
 [[0.88885217 0.98839265 0.35268335 0.16377398 0.16773071 0.3868651
  0.41339826 0.96221308 0.85636539 0.97450768]
 [0.57627582 0.03669536 0.33709872 0.86048054 0.5373653  0.62029502
  0.61686547 0.97376066 0.53436419 0.70013874]
 [0.09722227 0.44649727 0.89087636 0.72035431 0.47188698 0.73505639
  0.12505098 0.80481721 0.80534409 0.78027378]
 [0.54809591 0.03663617 0.81037068 0.05097061 0.96420407 0.64300754
  0.01606824 0.10645559 0.63213854 0.99779436]
 [0.08959214 0.06778541 0.67664674 0.62111311 0.86853777 0.86248186
  0.63170006 0.29988831 0.69102689 0.18426722]
 [0.10238737 0.69430887 0.42431208 0.75276387 0.07820468 0.99169532
  0.51442619 0.89232318 0.48100015 0.24582844]
 [0.32176996 0.89787262 0.70067136 0.19146868 0.35095999 0.03284749
  0.64158143 0.37258431 0.05471513 0.8245935 ]
 [0.43225106 0.74733324 0.60060529 0.47022605 0.10455414 0.62945712
  0.55667157 0.98823386 0.58272452 0.54235408]
 [0.94089667 0.47947243 0.19819302 0.39300325 0.29081985 0.50734352


13. Solve the system of equations:

  $3x - 11y = 3$

  $x - 4y = 6$

  using `numpy.linalg.solve`

In [102]:
A = np.array([[3, -11],[1,-4]])
b = np.array([[3], [6]])

x = np.linalg.solve(A, b)

print(x)

[[-54.]
 [-15.]]
